#!/usr/bin/env node
/*
 * build_index.js — gabungkan hasil crawl jadi assets/js/data.js
 * ---------------------------------------------------------------------------
 * Output: assets/js/data.js (SITE.*) untuk search engine clone.
 *   - SITE.lawsIndex  : semua metadata (161.969) -> search registry ringan
 *   - SITE.fullLaws   : UU (articles lengkap) -> halaman detail
 *   - search cocok di title + metadata; klik UU -> detail lengkap,
 *     klik non-UU -> link ke sumber pasal.id (krn articles belum di-crawl)
 */
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");
const META = path.join(ROOT, "data", "metadata");
const ART = path.join(ROOT, "data", "articles", "UU");

const metaFiles = fs.existsSync(META) ? fs.readdirSync(META).filter(f=>f.endsWith(".json")) : [];
let lawsIndex = [];
for (const f of metaFiles) {
  try {
    const arr = JSON.parse(fs.readFileSync(path.join(META, f), "utf8"));
    for (const l of arr) lawsIndex.push({
      type: l.type, number: l.number, year: l.year, title: l.title,
      status: l.status, frbr: l.frbr_uri,
      src: l.source_url || ("https://pasal.id" + l.frbr_uri)
    });
  } catch(e){ console.warn("skip", f, e.message); }
}
console.log("metadata laws:", lawsIndex.length);

let fullLaws = [];
if (fs.existsSync(ART)) {
  for (const f of fs.readdirSync(ART).filter(x=>x.endsWith(".json"))) {
    try {
      const d = JSON.parse(fs.readFileSync(path.join(ART, f), "utf8"));
      const w = d.work || {};
      const chapters = {};
      const pasals = (d.articles || []).filter(a=>a.type === "pasal" || a.type === "Pasal");
      for (const p of pasals) {
        const bab = p.parent_heading || "Pasal";
        (chapters[bab] = chapters[bab] || []).push({ n: p.number, t: p.content || "" });
      }
      fullLaws.push({
        type: w.type, number: w.number, year: w.year, title: w.title,
        status: w.status, frbr: w.frbr_uri,
        summary: (d.articles||[]).find(a=>a.type==="pembukaan")?.content || w.title,
        chapters: Object.entries(chapters).map(([bab, pasal])=>({bab, nama: bab, pasal})),
        src: w.source_url || ("https://pasal.id" + w.frbr_uri)
      });
    } catch(e){ console.warn("skip art", f); }
  }
}
console.log("full UU laws:", fullLaws.length);

const out = `// GENERATED by scripts/build_index.js — jangan edit manual.\n` +
  `const SITE = {\n` +
  `  lawsIndex: ${JSON.stringify(lawsIndex)},\n` +
  `  fullLaws: ${JSON.stringify(fullLaws)}\n` +
  `};\n`;
fs.writeFileSync(path.join(ROOT, "assets", "js", "data.js"), out);
console.log("written assets/js/data.js", out.length, "bytes");
